const lines = ["Oh, blimey! You're alive!",
"Mind yourself, mate! Askin' a sheila's name and you ain't giving your own first...",
"Cheers! My name's Marine! But what's this? I come down here, save your lives, and not even a \"thank you\"?",
"Aw, well, she'll be apples. I'm more interested in how you managed to find this island. Crikey! You didn't swim 'ere, did you?",
"This 'ere's Seagull Beach, near Windmill Village! You got any questions, I'm your gal, mate! After all, nothin' goes on 'round these parts without me knowing about it first, mate! As for Seagull Beach, well, I named it after the heaps of seagulls round 'ere. Ain't it just ripper?",
"Strewth! You don't even know where Southern Island is? It's in the middle of the ocean!",
"What? You want to come to my village? Well, then, my house is your house!",
"Awww! There it goes again. I really thought that I'd finally gotten it right...",
"You blind there, mate? I'm about to launch my pal here, the good ol' SS Marine! Last time, though, I made a few blues, and things went a bit crook, you know? Yeah, but she'll be right, then, won't she, mate? There ain't no one on the Seven Seas who can outrun... AHA! Now we've got some gas going!",
"Whoa! Yikes!",
"No worries, mates! Really! I've got everything under control 'ere! Holy dooley! Come on, Marine! I'm the one who built you! Stop being so stubborn! Sonic! Tails! Enough with the bludgering! Come 'ere and help me! Wait, me? Show weakness? No drama! Lemme just hit the brakes 'ere and...",
"Ahhh! My... my precious little baby! Look what's become of you! Ohhhh, what should I do? I can't rebuild 'er now! There's no way I can fix this!",
"Ohh, it's no use...",
"...no, it's no use! There ain't any materials left anyway.",
"The place I always go to get my building stuff has been blocked off, mate. I don't know exactly what 'appened, but the trail is blocked by boulders. Argh! And I... I can't get away from this place! I'll be stuck 'ere my whole life! I'm goin' troppo 'ere! I HAVE to get out!",
"Fair dinkum?! But... but the trail is blocked off! How will you...?",
"Well... all right, but...",
"Let's see... there should be some stuff lying around... Aha! This 'ere's what we need! Look for jewels or metal like this. Then I can give it a burl at puttin' it together.",
"Okay...",
"...?",
"....!!",
"Blimey! Tails, you can understand that? You're a fair dinkum genius!",
"Be careful!",
"Oh my gosh, really?",
"Well, Bob's your uncle! A waterbike?! For real?!",
"Bewdy! Sonic, did you hear that? A waterbike! That's pearl! That sounds so cool!",
"Yeah, anyhow, mate... Tails! Let's get going!",
"Wow, this waterbike's keen! Good on ya, Tails!",
"Enough with the chinwagging, you lot! Let's give it a whirl, eh? First off, let's go explore that island!",
"Yeah, s'right! I grew up always scratchin' my head over what's on that there island. It's the perfect starting point for my adventures!",
"Here begin the adventures of Captain Marine! Orright! I can't wait!",
"The jungle, ay? Oh, that's a beaut!",
"Sonic, Tails, look! Don't these 'ere mushrooms look tasty? They're all over the place!",
"No worries, mate! No worries! I'll stick within cooee.",
"Sonic! Wait! *huff huff* I just saw the keenest thing! Don't you want to hear about it?",
"'Course you do, mate! There's these mushrooms bigger than my house! The outside world has so much ace stuff in it! I'm having so much fun I'm nearly knackered!",
"Oh, hey, I have an idea! Why don't we call this 'ere place! \"Marine Island,\" ay? That way we can commemorate our arriving 'ere on our very first adventure!",
"G'day there, Sonic! Did you find any more Material?",
"Ace! Now we can use this 'ere to make ourselves a sailboat, ay?",
"Ay, I know that voice!",
"G'day, cobber! I haven't seen you in forever, mate!",
"Yeah! Tabby's a member if our village's youth association. We call it the Coconut Crew.",
"Yep! There's blokes 'ere are my assistants, Sonic and Tails.",
"Too right! Tails 'ere says that he can build us a real beaut of a boat, mate!",
"Okay! Time to launch, then! Let's mosey, you blokes!",
"Strewth! It really IS an island of machines! Reckon you've ever seen anything like that?",
"Hey, what's this handle do? Rrf! It's stuck and I can't turn it.",
"No drama, mate. No drama. Aha! 'ere another one! But it won't budge, either!",
"Oh! Sonic and Tails! Where've you two been? I've been worried sick about you two blokes!",
"Don't chuck a wobbly! You blokes get stressed out too easily.",
"! Oooooh! What's THAT, mate? That floating thing! Looks fun!",
"Come on, Sonic, let's have a go at it! It'll be a real ripsnorter!",
"Awwww! Sonic, that's not fair!",
"Nooo! I wanna go, too!",
"Sonic, you were tops! Since you're my best pupil, I'll let you 'ave a go at bein' leader when I step down. Not that I plan on calling it quits anythime soon, cobber! Ha ha ha ha ha!",
"Orright! More Material! I knew it'd be a ripper idea to come 'ere!",
"Heh heh heh. Oh, I can tell you that, mate!",
"There's gotta be some secret organization that's out to get me, yeah? They're jealous of my famous adventures, and they want to put a stop to them!",
"But I won't give up! Never! You can't make me! You no-good buncha dingos! My adventuring spirit will not be broken so easily!",
"Orright! Finally, our sailboat! We did a bonza job! Now, let's get to sailing mates!",
"Thanks for the hard yakka, there, crew. This is a beaut 'ere, it is!",
"Hmmm. Lesee...",
"Who's that?",
"Oh! If it ain't the spy! G'day there, cobber! Long time no see!",
"He's the Coconut Crew's, uh... Intelli... erm... Infiltra... Yeah, um. This bloke 'ere is the Colonel. He calls himself a spy.",
"Yeah, I still need to figure out where to go. Oy, Colonel, I bet you know tons of stuff, mate!",
"What? Oy, tell us, mate, mate! Please? Aren't we, like best buddies and all that?",
"Orright!",
"We've gotta give it a gander! I'm just dyin' for a good walkabout! Come on!",
"Hold it! If you're looking for a test of speed, you gotta go through me 'ere, first! I'm Captain Marine, the speed milk-drinking champion of Windmill Village!",
"Ha! You're just scared I'll beat ya, you mug! I don't blame you, though, really. Wouldn't want to lose to a Sheila like me after all that \"sultan\" yabber! He he he!",
"That's the spirit! 'ave a fair go, then! Okay, show 'em how it's done, Sonic! Don't be a bludger, now.",
"Hey, look! I think it can be budged!",
"But I wanna see what it does! ''Touches altar. Ground shakes'' ...aah!",
"Aaaaiiiieee! Earthquake!!",
"Crikey!! Something's comin' outta the water! What is that thing?!",
"Do my eyes deceive me...? ...or are we looking at a new challenge? Come on, you blokes!",
"All right, mateys! Prepare for landing!",
"This place is a beaut! I didn't think that underwater caves like this even existed! It's like something out of a storybook! This is the best adventure ever! Okay, mates, stay close! I'll lead the way!",
"Oy, I'M the captain! That means I get to lead!",
"But I want to lead from the front!",
"What?! Hey, you're right! I won't let these buggers get away that easily!",
"Aha! 'ere we go!",
"We should be asking you the same thing, old man!",
"See, old man, now you've got me all curious. What's your bizzo down 'ere, anyhow?",
"Oy, old man! That's a pretty nifty moustache you got there! ''Pulls Whisker's moustache'' Yoink!",
"Aaaaahhhhh!! ....",
"Th... that... That was... ripper! Do it again! C'mon, again!",
"Oy, hold it! Will someone please tell me what's going on 'ere?",
"And then I found and rescued you lot!",
"No worries, no worries! Just leave it all to me!",
"\"Little girl\"?! You gonna treat me just like any old sheila, then, are you? Sonic! Tails! Don't let her yabber about your captain like that! Get her!",
"Plasmalectra-what, now? What are you talking about, mate? And whatever all that means, when we're done with all that, can we get back to the fun?",
"A radio tower?! Do we get to listen to music and climb all around on it, mate?",
"Huh? What's up?",
"I love that tower! It's perfect for climbing, and the view from the top is a beaut!",
"What's electro... uh... magnetic mean?",
"......",
"Huh? What is it?",
"Uh, yeah! Let's go!",
"(Strewth... Are we really going? And there's going to be ghost ships?) (I can't be scared, though. I'm the captain!) (No ghosts can scare me off!)",
"Heeeeeey! Anybody there?",
"Awww, but I want to 'ave more of a gander about, mate! Maybe there's something else here!",
"Aw, you're no fun at all...",
"Hmm? Oy, it's Kylok!",
"Yeah, sure do! It's been yonks, mate!",
"What's the hold-up, Kylok? If you know something, then fire away, mate!",
"Aaaaah! Aaaaah!",
"(C-Come on, mate, don't bring that up! If you know where the ghost ship is at, tell me!)",
"O... orright! Let's go raid that ghost ship, then!",
"......",
"......",
"N-n-no, I'm f-fine. I just... You know, figured that, ah... Maybe you guys might want a crack at things? Sometimes the captain just needs a break, ay?",
"Blimey! The door's moving!",
"N-no, 'course not! It's not like I'm scared of g-g-g... ghosts or anything. Besides, even if there are any, ah, g-ghosts... I'll just b-b-beat 'em up! Yeah! Haha!",
"Y-yeah, sure!",
"(Well, thanks to my top-notch performance, nobody realizes that I'm really scared!) (I've gotta be careful, 'ere! I've got my captain's dignity to maintain, after all!)",
"H-hey! Oy! W-wait for me!",
"Huh? Oh, the bloke with the moustache again, ay?",
"Oy, come on, old man, don't be so mad! You can't even tell the difference, mate.",
"Eeeeek! 'ere it comes!",
"Yeah, yeah. Let's get back on the ship and put our noggins together! Let's go, Blaze!",
"Okay, mates! Let's go and get those pirates! I think they went... Hmm... That way!",
"Huh? What? But why?",
"Well, we'll just have to tempt fate, then! Make sail!",
"Orright, then! Just leave it to your captain! I'll come up with a plan!",
"Shh! Lemme think for a sec! Let's, um... huh? A hov... Hover-what?",
"Hov... hovercr... oh, fine! Let's get on with the adventure, you lot!",
"Yay! The hovercraft's done!",
"Huh? Which one?",
"What!? No way!",
"...",
"Nooooooooooooooooooooooooo! No no no no no! I'm goin' too! No matter what! My adventures have just started! They can't end here! I still need to see new things and explore and encounter new challenges and overcome them! I want adventure! I NEED adventure!",
"But... but...",
"What... what's that?",
"Is that all? No worries, then! I'm the captain, after all, right, mate?",
"Orright, so now that that's settled, let's go, you lot!",
"Huh? Where... uh... Over there! I've got this hunch that there are pirates over there! Heaps of 'em!",
"Oy, wait just a minute, mate! Don't you trust your captain's hunch!? Oy!",
"Whoooooa! It's a huge field of white!",
"Oooh! So then this is \"snow,\" ay? Oh, it's all chilly! This is so c-c-cold! We should build a snowman to commemorate my arrival here, ay, mate?",
"Check it out! You just roll it and roll it and it keeps on gettin' bigger and bigger!",
"Oh, I know, I'll be okay! Hm? Hey, look at that! It's a house made of ice! Strewth! I'm gonna go check it out!",
"H... hey! You lot! *huff huff* We've... we've got trouble!",
"I... I knocked on the door, and I didn't get an answer... So, I took a peep inside... And nobody's in there!",
"I thought it was weird, yeah, so I looked at some other houses, and they're all empty!",
"Aaahhhhh! S-S-Sonic! Look!",
"in... in the ice! Th-there are people in there!",
"You're only just kenning that now, mate?!",
"Oh, no worries, eh! My mates 'ere were able to handle it all in a jiffy, yeah.",
"Those nasty little buggers!",
"What's that you reckon, mate? Those pirates 'ave gotta be in those ruins! Think about it, mate: legends! When has a legend ever not been true, huh? HUH?!",
"Y-yeah, mate...",
"Oy, this bloke's a riot! I say we add him to our crew!",
"Waaaah! Who... who are you?",
"No worries, though, yeah? I was only an ankle biter back then, after all.",
"Orright, let's set sail, crew! Thanks for the help there, Daikun.",
"You should come back to the village sometime, mate. It'll be the bee's knees!",
"Aw, quit yer fussin'! I think the sunlight makes it seem a fair bit safer, if you ask me.",
"Hm? Hey, mates, take a gander at that!",
"Oh, ripper! This could be some huge treasure, reckon? Think we oughta nick it, mates?",
"Aw, but this 'ere could be the discovery of the century, don't you reckon?",
"Aww, how come I'm always gettin' the rough end of the pineapple from you, eh? I'm not gonna get my paws all over it TOO much.",
"Come on, Blaze. No worries, really!",
"...wha?",
"Aaaahhh!",
"Oh, CRIKEY! Th-th-those are clouds!",
"Blaze, is something wrong?",
"Oy, Blaze! Don't shove!",
"Aw, now she's flipped back to her normal self...",
"Oy, it's that bloke with the face-fuzz again!",
"Right, then! C'mon, mates! Let's get ourselves on a walkabout 'ere, yeah?",
"Yeah, orright, Blaze. Sheesh. You could talk the leg off an iron pot, you know!",
"Oy, mate! 'ave yourself a peek at this 'ere!",
"Orright, then, chumps, step aside and let Captain Marine take a butcher's at this 'ere.",
"Hmmm... Uh-huh...? (Crikey, this don't make a lick of sense! I'm really up the gumtree now!)",
"Oy, howzat?! Don't be such a stickybeak, Blaze!",
"North, eh? That's that way!",
"Underwater? How the heck're we supposed to get down there?",
"(Right, now what's all this yabber about a summerine?)",
"Oy, mate! 'ave yourself a peek at this 'ere!",
"Orright, then, chumps, step aside and let Captain Marine take a butcher's at this 'ere.",
"Hmmm... Uh-huh...? (Crikey, this don't make a lick of sense! I'm really up the gumtree now!)",
"Oy, howzat?! Don't be such a stickybeak, Blaze!",
"North, eh? That's that way!",
"D'ya think the bloke with the whiskers really was just on a bit of a walkabout?",
"Eeeeek! Oy, it's shakin'!",
"I don't reckon, mate! I'm stickin' right 'ere!",
"Y-y-yeah, she'll be apples... But blimey, that was a bit of a rough patch. I'm still shaking and jittering 'ere...",
"Nah, mate, they're about as rare as hen's teeth.",
"Right-o, cobbers! Just leave it to me, yeah?",
"Aw, strewth! A real honest summerine!",
"This looks like a heavy bugger though. When it goes down, how's it gonna come back up?",
"Fair dinkum?! I get to see all the little fishies and the big ol' sharkies and all? I wanna get goin' right away!",
"Hey now, no need to get all agro on me. Your captain's just being a little joker. Tehehehe...",
"Orright, then! Time for Captain Marine's maiden voyage under the sea!",
"Oy, it's the fuzzy-faced bloke again!",
"Oy, fuzzy, gimme a fair go at this.",
"How is it that you lot are able to get in 'ere, then?",
"You're a funny little drongo there, mate, you know that?",
"Get back here, mate! Keep on with the yammering!",
"Just like old-fashioned fossicking! Let's have a go at it, then!",
"Oy, don't you think that's pretty keen, there, mate? Lemme 'ave a gander!",
"Oy, don't you think that's pretty keen, there, mate? Lemme 'ave a gander!",
"Orright! On with the treasure hunt!",
"Orright! On with the treasure hunt!",
"Orright! On with the treasure hunt!",
"Oy, now I'm all knackered...",
"That was some real hard yakka, though, eh? I wonder why all the need for a walkabout.",
"Ancient ruins! That's beaut! What'll they be like, d'ya reckon? Oy, I can't wait!",
"Aw, she'll be apples, Blaze! Ol' fuzzy-face won't know what hit 'im! Not once Captain Marine here conks him good!",
"Oy, what's that look for, there, mate?",
"...!!",
"... ...",
"... ... ... Whoa, hey, where's all this coming from, then? You're just yanking my chain, right? I'm still game! I'm ridgy-didge!",
"You said we were ready to go, mate, so let's go! There's no way I'm packing up and quitting this 'ere adventure!",
"Crikey, what's with the shouting all of a sudden?",
"A... a nuisance...? Wh... what do you mean?",
"I... I'm not a nuisance! I... I mean... I was your captain, right? I... I was always looking out for you lot! Right? Come on, tell her, Sonic! Tails!",
"You... you all DO think I'm a nuisance, don't you? You... you're all a bunch of drongos!",
"*Sniff* I... I can't just give up 'ere... I've gotta prove my worth as a captain, yeah? I gotta go and stop that ol' fuzzy-face!",
"You can't escape from me, you no-good pirates!",
"I'll teach you a lesson, you... you... you mustachioed menace!",
"N-no! L-let me go!!",
"You... bushy-faced freak!",
"Wh-what are you going to do to me?",
"Nooo! Anything but that!",
"Y-y-you guys! You came for me! Oh, I knew you would, mates!",
"S-sorry!",
"Wh-wh-wh...",
"W-well, I mean, I just figured since... well, I'm the captain and all... I thought I could have my big moment, and if I just did a little bit more, then...",
"I... I know. I didn't...",
"Aw, well, all right. I guess I can do that. A little. Hehehe!",
"Heehee!",
"Are you talking about THIS scepter? Ta-daah!",
"The one and only! I nicked it while I was captured, when ol' whiskers wasn't looking!",
"Aww, heh heh! No drama! Anyway, 'ere you go, Blaze; one Jeweled Scepter!",
"Heheh!",
"Y-yeah...",
"Yeah! I can't wait until I get home and tell everyone about all my ripper adventures!",
"(Of course, no one's going to believe that part about my getting the scepter back.) (Still, I guess it can't be helped so long as I'm still a kid...)",
"Oh, nothing! I'm coming! Just you watch, mates! I'll become a captain for real!",
"Not at all! With the pirates gone, it's not like I don't have free time now. While you're 'ere, would you like to help me work on my ship?",
"Of course! I need a new ship to go on new adventures! The SS Super-Marine!",
"Well, you saw how the first ship was all crook. So, now I just gotta make a better one!",
"Well, hold on just a sec. I don't think it's all THAT bad a sign.",
"Another earthquake?",
"Oh, I hope so...",
"Who the heck is this guy? And what was he doing lurking under the water like that?",
"(He looks just like that moustached pirate bloke!)",
"(Ooh, boy, now I'm seeing double! Maybe I need to get my head checked... ugh...)",
"Ahh! It's another earthquake!",
"Hold it right there, you twin moustached monkeys!",
"Blaze needs that scepter back! And I still don't know what this \"Eggmanland\" thing is!",
"Wait up! You still haven't told me what Eggmanland is!",
"ANOTHER earthquake?! Eeeek!",
"Oy, you hear that, Eggman? We've coming after you! And I'm gonna make you tell me what Eggmanland is!",
"Strewth, Tails! Is there anything that you CAN'T build, mate?",
"Oooh, this is going to be simply ripper! I wonder what it's like underground!",
"Sonic! Look!",
"Ahhhh! Wh-wha-what... what IS this thing... Rrrrgh!",
"Hah! How do you like that, Eggman?! Sonic! Blaze! Now's your chance!",
"Heeey!",
"Wait! Stop the boat!",
"What are you talking about, mate? I can't let you leave without seeing you off!",
"It's the SS Super-Marine! It took days and days to finish, but doesn't she look a beaut?",
"Yeah, well, I can't leave any stone unturned if I'm going to explore the world! And to do that, I need my own ship, after all!",
"It's okay. I know what you're thinking.",
"I don't have what it takes. I don't think I can do all this adventuring on my own.",
"But I'm not going to give up. I need to keep trying harder and harder until I can do it! I mean, it took everything I had just to build this ship! Heehee!",
"Sonic... Tails...",
"Th... thanks, guys. You're the best mates ever. *sniff!* And I won't just focus on adventures, either! I promise that I'll study hard, too!",
"And next time we see each other, don't blown away by how much I've grown up!",
"And... and I... I'll... I'll b-be... *sniff!*",
"...",
"S... Sonic...",
"Tails... ... ... You're right! I'll make sure that I'll get to see you guys soon! I'll be sure to find you, no matter where you are! Even if I have to go to your world!",
"Bye bye!",
"See you later!"]

export default lines;