name: "Post to Bluesky"

on: workflow_dispatch
on:
  schedule:
    - cron: "30 1,5,9,13,17,21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: yarn install
      - run: yarn build
      - name: Send post
        run: yarn start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}